### ISSUE TITLE
finishing up FLIR extractor

### ISSUE THREAD

**Issue by max-zilla** [terraref/extractors-multispectral#1]
@ZongyangLi just FYI I have moved your FLIR code here. I am reviewing + making some changes, but this will become primary version of your script so eventually we can delete from computing-pipeline.

I'll make a pull request of my changes so you can see what I did/why. Then we are ready to deploy!

**Comment by ZongyangLi** [comment]
Great!

**Comment by max-zilla** [comment]
I left a comment in the other thread - seems like the sensor might be having metadata problems.

But you can see what I've changed here:
https://github.com/terraref/extractors-multispectral/compare/final-updates-before-deployment

So far just updated a tiny piece of check_message(). Looks good so far though.
